#!/bin/sh /etc/rc.common

# shellcheck disable=SC2034
USE_PROCD=1
START=99

prog_name="yubikey-hack"
bin="/usr/bin/$prog_name"

start_service() {
    procd_open_instance
    procd_set_param command "$bin"
    procd_set_param stdout 1
    procd_set_param stderr 1

    file=$(cat /etc/yubikey-hack/env)
    for line in $file; do
        procd_append_param env "$line"
    done

    procd_close_instance
}
