#!/bin/sh /etc/rc.common
# Copyright (C) 2010-2015 OpenWrt.org

# shellcheck disable=SC2034
START=99

# shellcheck disable=SC2034
USE_PROCD=1
PROG=/usr/bin/yubikey-hack

start_service() {
    procd_open_instance
    procd_set_param command "$PROG"
    procd_set_param respawn
    procd_set_param stdout 1

    file=$(cat /etc/yubikey-hack/env)
    for line in $file; do
        procd_append_param env "$line"
    done

    procd_close_instance
}
